// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    partial class TaskManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateRemove")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_remove");

                    b.Property<int>("IdAuthorCreateDocument")
                        .HasColumnType("integer")
                        .HasColumnName("id_author_create_document");

                    b.Property<int?>("IdAuthorRemoveDocument")
                        .HasColumnType("integer")
                        .HasColumnName("id_author_remove_document");

                    b.Property<int>("IdSourceResponsibleEmployee")
                        .HasColumnType("integer")
                        .HasColumnName("id_source_responsible_employee");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsUnderControl")
                        .HasColumnType("boolean")
                        .HasColumnName("is_under_control");

                    b.Property<DateOnly?>("OutputOutgoingDate")
                        .HasColumnType("date")
                        .HasColumnName("output_outgoing_date");

                    b.Property<string>("OutputOutgoingNumber")
                        .HasColumnType("text")
                        .HasColumnName("output_outgoing_number");

                    b.Property<string>("OutputResponseSubmissionMark")
                        .HasColumnType("text")
                        .HasColumnName("output_response_submission_mark");

                    b.Property<string>("OutputSentTo")
                        .HasColumnType("text")
                        .HasColumnName("output_sent_to");

                    b.Property<string>("OutputTransferredInWorkOrder")
                        .HasColumnType("text")
                        .HasColumnName("output_transferred_in_work_order");

                    b.Property<string>("SourceCustomer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_customer");

                    b.Property<DateOnly>("SourceDueDate")
                        .HasColumnType("date")
                        .HasColumnName("source_due_date");

                    b.Property<bool>("SourceIsExternal")
                        .HasColumnType("boolean")
                        .HasColumnName("source_is_external");

                    b.Property<DateOnly>("SourceOutgoingDocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("source_outgoing_document_date");

                    b.Property<string>("SourceOutgoingDocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_outgoing_document_number");

                    b.Property<DateOnly>("SourceOutputDocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("source_output_document_date");

                    b.Property<string>("SourceOutputDocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_output_document_number");

                    b.Property<string>("SourceTaskText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_task_text");

                    b.HasKey("Id");

                    b.HasIndex("IdAuthorCreateDocument");

                    b.HasIndex("IdAuthorRemoveDocument");

                    b.HasIndex("IdSourceResponsibleEmployee");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("TaskManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("TaskManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaskManager.Models.Document", b =>
                {
                    b.HasOne("TaskManager.Models.User", "AuthorCreateDocument")
                        .WithMany()
                        .HasForeignKey("IdAuthorCreateDocument")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManager.Models.User", "AuthorRemoveDocument")
                        .WithMany()
                        .HasForeignKey("IdAuthorRemoveDocument")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskManager.Models.Employee", "SourceResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("IdSourceResponsibleEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorCreateDocument");

                    b.Navigation("AuthorRemoveDocument");

                    b.Navigation("SourceResponsibleEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
