// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Persistence.Data;

#nullable disable

namespace TaskManager.Persistence.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    [Migration("20251212101920_popkek")]
    partial class popkek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор документа.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_employee_id")
                        .HasComment("Идентификатор сотрудника, который создал документ.");

                    b.Property<string>("CustomerInputDocument")
                        .HasColumnType("text")
                        .HasColumnName("customer_input_document")
                        .HasComment("Заказчик. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<string>("DocumentSummaryInputDocument")
                        .HasColumnType("text")
                        .HasColumnName("document_summary_input_document")
                        .HasComment("Краткое содержание документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<string>("DocumentSummaryOutputDocument")
                        .HasColumnType("text")
                        .HasColumnName("document_summary_output_document")
                        .HasComment("Краткое содержание документа. Выходные данные документа. Заполняет исполнитель.");

                    b.Property<int?>("IdResponsibleEmployeeInputDocument")
                        .HasColumnType("integer")
                        .HasColumnName("id_responsible_employee_input_document")
                        .HasComment("Идентификатор ответственного сотрудника. Входные данные документа. Заполняет исполнитель.");

                    b.Property<DateOnly>("IncomingDocumentDateInputDocument")
                        .HasColumnType("date")
                        .HasColumnName("incoming_document_date_input_document")
                        .HasComment("Дата входящего документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<string>("IncomingDocumentNumberInputDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incoming_document_number_input_document")
                        .HasComment("Входящий номер документа ВХ(46 ЦНИИ). Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed")
                        .HasComment("Признак завершения задачи. Заполняет исполнитель.");

                    b.Property<bool>("IsExternalDocumentInputDocument")
                        .HasColumnType("boolean")
                        .HasColumnName("is_external_document_input_document")
                        .HasComment("Признак внешнего документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<bool>("IsExternalDocumentOutputDocument")
                        .HasColumnType("boolean")
                        .HasColumnName("is_external_document_output_document")
                        .HasComment("Признак внешнего документа. Выходные данные документа. Заполняет исполнитель.");

                    b.Property<bool>("IsUnderControl")
                        .HasColumnType("boolean")
                        .HasColumnName("is_under_control")
                        .HasComment("Признак нахождения задачи на контроле. Выходные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<int?>("LastEditedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("last_edited_by_employee_id")
                        .HasComment("Идентификатор сотрудника, который последним редактировал документ.");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_edited_date_time")
                        .HasComment("Дата и время последнего редактирования документа.");

                    b.Property<DateOnly?>("OutgoingDocumentDateOutputDocument")
                        .HasColumnType("date")
                        .HasColumnName("outgoing_document_date_output_document")
                        .HasComment("Дата исходящего документа. Выходные данные документа. Заполняет исполнитель.");

                    b.Property<string>("OutgoingDocumentNumberInputDocument")
                        .HasColumnType("text")
                        .HasColumnName("outgoing_document_number_input_document")
                        .HasComment("Исходный номер документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<string>("OutgoingDocumentNumberOutputDocument")
                        .HasColumnType("text")
                        .HasColumnName("outgoing_document_number_output_document")
                        .HasComment("Исходящий номер документа Исх(46 ЦНИИ). Выходные данные документа. Заполняет исполнитель.");

                    b.Property<string>("RecipientOutputDocument")
                        .HasColumnType("text")
                        .HasColumnName("recipient_output_document")
                        .HasComment("Получатель. Выходные данные документа. Заполняет исполнитель.");

                    b.Property<DateTime?>("RemoveDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("remove_date_time")
                        .HasComment("Дата удаления документа.");

                    b.Property<int?>("RemovedByEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("removed_by_employee_id")
                        .HasComment("Идентификатор сотрудника, который удалил запись.");

                    b.Property<string>("ResponsibleDepartmentInputDocument")
                        .HasColumnType("text")
                        .HasColumnName("responsible_department_input_document")
                        .HasComment("ответственный отдел входящего документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<string>("ResponsibleDepartmentsInputDocument")
                        .HasColumnType("text")
                        .HasColumnName("responsible_departments_input_document")
                        .HasComment("Привлеченные отделы. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<DateOnly?>("SourceDocumentDateInputDocument")
                        .HasColumnType("date")
                        .HasColumnName("source_document_date_input_document")
                        .HasComment("Дата исходного документа. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.Property<DateOnly>("TaskDueDateInputDocument")
                        .HasColumnType("date")
                        .HasColumnName("task_due_date_input_document")
                        .HasComment("Срок выполнения задачи. Входные данные документа. Заполняет хозяин записи (делопроизводитель).");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("IdResponsibleEmployeeInputDocument");

                    b.HasIndex("LastEditedByEmployeeId");

                    b.HasIndex("RemovedByEmployeeId");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasComment("Таблица для хранения документов системы TaskManager");
                        });
                });

            modelBuilder.Entity("TaskManager.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор сотрудника");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department")
                        .HasComment("Подразделение или отдел, в котором работает сотрудник");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name")
                        .HasComment("Полное имя сотрудника (фамилия и инициалы)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login")
                        .HasComment("Логин сотрудника для входа в систему");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password")
                        .HasComment("Пароль сотрудника для входа в систему");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role")
                        .HasComment("Тип сотрудника (роль в системе)");

                    b.HasKey("Id");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasComment("Таблица для хранения данных сотрудников системы TaskManager");
                        });
                });

            modelBuilder.Entity("TaskManager.Domain.Entities.Document", b =>
                {
                    b.HasOne("TaskManager.Domain.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManager.Domain.Entities.Employee", "ResponsibleEmployeeInputDocument")
                        .WithMany()
                        .HasForeignKey("IdResponsibleEmployeeInputDocument")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskManager.Domain.Entities.Employee", "LastEditedByEmployee")
                        .WithMany()
                        .HasForeignKey("LastEditedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskManager.Domain.Entities.Employee", "RemovedByEmployee")
                        .WithMany()
                        .HasForeignKey("RemovedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("LastEditedByEmployee");

                    b.Navigation("RemovedByEmployee");

                    b.Navigation("ResponsibleEmployeeInputDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
